version: '3.8'

volumes:
  sqlvolume:

networks:
  grains-backend:
    external: true

services:
  sql:
    image: "postgres"
    restart: on-failure
    hostname: "sql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=grains
    command: ["-c", "max_connections=2000", "-c", "shared_buffers=2560MB",]
    volumes:
      - sqlvolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
     grains-backend:
      aliases:
        - grains-sql