version: "3.3"

services:
  test_app:
    build:
      context:  ./src
      dockerfile: ./TestWebAPI/Dockerfile
    image: test_app
    ports:
      - "5000:80"
    depends_on: 
      - silo
    links:
      - silo
  silo:
    build:
      context: ./src
      dockerfile: ./SiloHost/Dockerfile
    image: silo
    ports:
      - "30000:30000"
      - "11111:11111"