version: '3.8'

networks:
  grains-backend:
    external: true

services:   
  orleanshost:
    image: ${DOCKER_REGISTRY-}host
    build:
      context: .
      dockerfile: OrleansHost/Dockerfile    
    env_file:
      - OrleansHost/orleanshost.local.env
    restart: on-failure
    ports:
      - "11111:11111"
      - "30000:30000"
    networks:
     grains-backend:
      aliases:
      - orleanshost  
    
  orleansclient:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: OrleansClient/Dockerfile
    env_file:
      - OrleansClient/orleansclient.local.env
    depends_on:      
      - orleanshost
    restart: on-failure
    ports:
      - "5001:80"
    networks:
      - grains-backend      