version: '3.8'

networks:
  grains-backend:
    external: true

services:   
  selfhosted:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: SelfHosted/Dockerfile    
    env_file:
      - SelfHosted/selfhosted.local.env
    restart: on-failure
    ports:
      - "11111:11111"
      - "30000:30000"
    networks:
     grains-backend:
      aliases:
      - selfhosted  
    
  cohosted:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: CoHosted/Dockerfile
    env_file:
      - CoHosted/cohosted.local.env
    depends_on:      
      - selfhosted
    restart: on-failure
    ports:
      - "5001:80"
      - "11112:11112"
      - "30001:30001"
    networks:
      - grains-backend      