version: '3.8'

networks:
  grains-backend:
    external: true

services:   
  selfhosted:
    image: ${DOCKER_REGISTRY-}selfhosted
    build:
      context: .
      dockerfile: SelfHosted/Dockerfile    
    env_file:
      - SelfHosted/selfhosted.local.env
    restart: on-failure
    ports:
      - "11112:11112"
    networks:
      - grains-backend
    
  cohosted:
    image: ${DOCKER_REGISTRY-}cohosted
    build:
      context: .
      dockerfile: CoHosted/Dockerfile
    env_file:
      - CoHosted/cohosted.local.env
    depends_on:      
      - selfhosted
    restart: on-failure
    ports:
      - "5001:5001"
      - "11111:11111"
    networks:
      - grains-backend      