version: '3.4'

services:
  orleansclient:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: OrleansClient/Dockerfile
    env_file:
      - OrleansClient/orleansclient.local.env
    depends_on:
      - sql
    restart: on-failure
    ports:
      - "5000:80"
    networks:
      - backend
          
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: "sql"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345(!)a
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      backend:
        aliases:
          - sql

volumes:
  sqlvolume:

networks:
  backend: