apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selfhosted
  name: selfhosted
  namespace: grains
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: selfhosted
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        orleans/clusterId: grains
        orleans/serviceId: selfhosted
        app: selfhosted
    spec:
      containers:
        - env:
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: IS_KUBERNETES_ORLEANS_HOSTING
              value: "true"
            - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
              value: "30"
          envFrom:
            - configMapRef:
                name: general
            - configMapRef:
                name: selfhosted
          image: volinc/grains:selfhosted
          imagePullPolicy: IfNotPresent
          args:
            - dotnet
            - "SelfHosted/SelfHosted.dll"
          name: selfhosted
          ports:
            - containerPort: 11111
              name: 11111tcp0
              protocol: TCP
            - containerPort: 30001
              name: 30001tcp1
              protocol: TCP
          readinessProbe:
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 2
            tcpSocket:
              port: 30001
            timeoutSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 30001
            initialDelaySeconds: 10
            periodSeconds: 3
          resources: { }
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsConfig: { }
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: selfhosted
  namespace: grains
spec:
  ports:
    - name: 11111tcp0
      port: 11111
      protocol: TCP
      targetPort: 11111
    - name: 30001tcp1
      port: 30001
      protocol: TCP
      targetPort: 30001
  selector:
    app: selfhosted
  sessionAffinity: None
  type: ClusterIP
